import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

describe('UnifiedNotification visual contract', () => {
  const source = readFileSync(resolve(process.cwd(), 'src/components/UnifiedNotification.css'), 'utf-8');
  const componentSource = readFileSync(resolve(process.cwd(), 'src/components/UnifiedNotification.tsx'), 'utf-8');

  it('uses a top-center single-line Codex-like notification with control radius', () => {
    expect(source).toContain('left: 50%');
    expect(source).toContain('transform: translateX(-50%)');
    expect(source).toContain('align-items: center');
    expect(source).toContain('width: min(420px, calc(100vw - 24px))');
    expect(source).toContain('max-width: min(320px, calc(100vw - 24px))');
    expect(source).toContain('min-height: 28px');
    expect(source).toContain('border-radius: var(--radius-shell-control);');
    expect(source).toContain('padding: 4px 12px');
    expect(source).toContain('white-space: nowrap');
    expect(source).toContain('text-overflow: ellipsis');
    expect(source).toContain('.unified-notification-text');
    expect(source).not.toContain('min-width: min(280px, 100%)');
    expect(source).not.toContain('width: 100%');
    expect(source).not.toContain('.unified-notification-title');
    expect(source).not.toContain('.unified-notification-message');
    expect(source).toContain('.unified-notification-close');
    expect(source).toContain('.unified-notification-close-icon');
    expect(source).toContain('width: 18px');
    expect(source).toContain('height: 18px');
    expect(source).toContain('--notif-stroke-color: hsl(var(--success)');
    expect(source).toContain('--notif-stroke-color: hsl(var(--warning)');
    expect(source).toContain('--notif-stroke-color: hsl(var(--destructive)');
    expect(source).toContain('.unified-notification-neutral');
    expect(source).not.toContain('border-color: hsl(var(--info)');
    expect(source).not.toContain('.unified-notification-border-neutral');
    expect(source).not.toContain('rgb(28 28 28 / 0.72)');
    expect(source).toContain('unified-notification-action');
    expect(source).toContain('.unified-notification-icon');
    expect(source).toContain('.unified-notification-progress');
    expect(source).toContain('.unified-notification-count');
    expect(source).toContain('--notif-stroke-color');
    expect(source).toContain('border: 1px solid var(--notif-stroke-color);');
    expect(source).toContain('color: var(--notif-stroke-color);');
    expect(source).toContain('linear-gradient(90deg, transparent 0%, var(--notif-stroke-color)');
    expect(source).toContain('--notif-progress-duration');
    expect(source).toContain('--notif-progress-play-state');
    expect(source).not.toContain('--notif-icon-color');
    expect(source).not.toContain('.unified-notification::before');
    expect(componentSource).toContain('GlobalNotificationIconMode');
    expect(componentSource).toContain('GlobalNotificationProgressMode');
    expect(componentSource).toContain('shouldShowIcon');
    expect(componentSource).toContain('shouldShowProgress');
    expect(componentSource).toContain('icon?: GlobalNotificationIconMode');
    expect(componentSource).toContain('progress?: GlobalNotificationProgressMode');
    expect(componentSource).toContain("from '@phosphor-icons/react'");
    expect(componentSource).toContain('CheckCircle');
    expect(componentSource).toContain('WarningCircle');
    expect(componentSource).toContain('Warning');
    expect(componentSource).toContain('Info');
    expect(componentSource).toContain('weight="regular"');
    expect(componentSource).not.toContain("from 'lucide-react'");
    expect(componentSource).not.toContain('CheckCircle2');
    expect(componentSource).not.toContain('CircleAlert');
    expect(componentSource).not.toContain('TriangleAlert');
    expect(componentSource).toContain('unified-notification-icon');
    expect(componentSource).toContain('unified-notification-progress');
    expect(componentSource).toContain('unified-notification-count');
    expect(componentSource).toContain('icon: options?.icon');
    expect(componentSource).toContain('progress: options?.progress');
    expect(componentSource).not.toContain('unified-notification-title');
    expect(componentSource).not.toContain('unified-notification-message');
    expect(componentSource).toContain('unified-notification-close');
    expect(componentSource).toContain('aria-label="关闭通知"');
    expect(componentSource).toContain('<X className="unified-notification-close-icon"');
    expect(componentSource).toContain('unified-notification-text');
    expect(componentSource).toContain("info: 'unified-notification-neutral'");
    expect(componentSource).not.toContain('unified-notification-border-neutral');
  });
});
